"""`make configure` -- interactive configuration written to a gitignored .env.

Also supports non-interactive use: if the lakeFS variables are already set in the
environment, it validates and (re)writes .env without prompting. The lakeFS
secret key is read without echo and is never printed.
"""

from __future__ import annotations

import getpass
import os
import sys

from common.config import SAMPLE_ROOT
from gateway.lakefs_client import LakeFSClient, LakeFSError
from orchestrator.repository import NO_REPOS_MESSAGE, list_repository_ids

ENV_PATH = SAMPLE_ROOT / ".env"

AWS_DEFAULTS = {
    "AWS_PROFILE": "",
    "AWS_REGION": "us-west-2",
    "BEDROCK_MODEL_ID": "us.anthropic.claude-opus-5",
    "AGENTCORE_RESOURCE_PREFIX": "agentcore-data-pr",
}


def _prompt(label: str, default: str = "", interactive: bool = True) -> str:
    if not interactive:
        return default
    suffix = f" [{default}]" if default else ""
    val = input(f"{label}{suffix}: ").strip()
    return val or default


def _choose_repository(repos: list[str], interactive: bool) -> str:
    if len(repos) == 1:
        print(f"Using the only accessible repository: {repos[0]}")
        return repos[0]
    if not interactive:
        raise SystemExit(
            "Multiple repositories accessible; set LAKEFS_REPOSITORY for "
            "non-interactive configuration."
        )
    print("Accessible repositories:")
    for i, r in enumerate(repos, 1):
        print(f"  {i}. {r}")
    while True:
        choice = input(f"Select a repository [1-{len(repos)}]: ").strip()
        if choice.isdigit() and 1 <= int(choice) <= len(repos):
            return repos[int(choice) - 1]
        print("Invalid selection.")


def _write_env(values: dict[str, str]) -> None:
    lines = [
        "# Generated by `make configure`. Contains SENSITIVE credentials.",
        "# This file is gitignored and must NEVER be committed.",
        "",
    ]
    for key in (
        "LAKEFS_ENDPOINT",
        "LAKEFS_ACCESS_KEY_ID",
        "LAKEFS_SECRET_ACCESS_KEY",
        "LAKEFS_REPOSITORY",
        "LAKEFS_SOURCE_BRANCH",
        "AWS_PROFILE",
        "AWS_REGION",
        "BEDROCK_MODEL_ID",
        "AGENTCORE_RESOURCE_PREFIX",
    ):
        lines.append(f"{key}={values.get(key, '')}")
    ENV_PATH.write_text("\n".join(lines) + "\n")
    os.chmod(ENV_PATH, 0o600)


def main() -> int:
    interactive = sys.stdin.isatty()
    print("=== Configure: Agentic Data PRs with AgentCore + lakeFS Cloud ===\n")

    endpoint = _prompt(
        "lakeFS Cloud endpoint",
        os.getenv("LAKEFS_ENDPOINT", ""),
        interactive,
    ).rstrip("/")
    access_key = _prompt(
        "lakeFS access key id", os.getenv("LAKEFS_ACCESS_KEY_ID", ""), interactive
    )

    secret = os.getenv("LAKEFS_SECRET_ACCESS_KEY", "")
    if interactive:
        entered = getpass.getpass("lakeFS secret access key (input hidden): ")
        secret = entered or secret

    if not (endpoint and access_key and secret):
        print("\nERROR: endpoint, access key id, and secret key are all required.")
        return 2

    print("\nValidating authentication and listing repositories...")
    client = LakeFSClient(endpoint, access_key, secret)
    try:
        repos = list_repository_ids(client)
    except LakeFSError as exc:
        print(f"ERROR: could not authenticate to lakeFS: {exc}")
        return 2

    if not repos:
        print(NO_REPOS_MESSAGE)
        return 2

    configured_repo = os.getenv("LAKEFS_REPOSITORY", "").strip()
    if configured_repo and configured_repo in repos:
        repository = configured_repo
        print(f"Using configured repository: {repository}")
    else:
        repository = _choose_repository(repos, interactive)

    source_branch = _prompt(
        "source branch", os.getenv("LAKEFS_SOURCE_BRANCH", "main"), interactive
    )

    values = {
        "LAKEFS_ENDPOINT": endpoint,
        "LAKEFS_ACCESS_KEY_ID": access_key,
        "LAKEFS_SECRET_ACCESS_KEY": secret,
        "LAKEFS_REPOSITORY": repository,
        "LAKEFS_SOURCE_BRANCH": source_branch,
    }
    for k, default in AWS_DEFAULTS.items():
        values[k] = os.getenv(k, default)

    _write_env(values)
    print(f"\nWrote {ENV_PATH} (permissions 600).")
    print(
        "\nWARNING: .env contains your lakeFS secret key. It is gitignored; never "
        "commit it or share it. The secret key was not printed."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
